### Intro to SQL Workshop Queries

This notebook contains the queries we wrote during the Intro to SQL workshop. 

In the workshop, we ran these through DB Browser for SQLite. Here, I'm running them through python and pandas, but the queries themselves are transferable - you can copy and paste the SQL and it should run fine in DB Browser or other IDEs (the portability of SQL is actually one of its benefits). 

If you want to run this specific workbook, you'll need to create a data directory (at the same level as this notebook) with a copy of the portal_mammals.sqlite file (see http://datacarpentry.org/sql-ecology-lesson/setup.html for instructions on getting this file).

In [1]:
import sqlite3
import pandas as pd

In [2]:
conn = sqlite3.connect("data/portal_mammals.sqlite")

In [3]:
pd.read_sql_query("""
    SELECT species, genus, taxa FROM species 
""", conn)

            species             genus     taxa
0         bilineata        Amphispiza     Bird
1           harrisi  Ammospermophilus   Rodent
2        savannarum        Ammodramus     Bird
3           taylori           Baiomys   Rodent
4   brunneicapillus   Campylorhynchus     Bird
5       melanocorys       Calamospiza     Bird
6          squamata        Callipepla     Bird
7        scutalatus          Crotalus  Reptile
8            tigris     Cnemidophorus  Reptile
9         uniparens     Cnemidophorus  Reptile
10          viridis          Crotalus  Reptile
11         merriami         Dipodomys   Rodent
12            ordii         Dipodomys   Rodent
13      spectabilis         Dipodomys   Rodent
14              sp.         Dipodomys   Rodent
15        obsoletus           Eumeces  Reptile
16            silus          Gambelia  Reptile
17         albigula           Neotoma   Rodent
18              sp.           Neotoma   Rodent
19      leucogaster         Onychomys   Rodent
20         torridus         Onychomys   Rodent
21              sp.         Onychomys   Rodent
22          baileyi       Chaetodipus   Rodent
23        chlorurus            Pipilo     Bird
24         eremicus        Peromyscus   Rodent
25           flavus       Perognathus   Rodent
26        gramineus         Pooecetes     Bird
27         hispidus       Perognathus   Rodent
28      intermedius       Chaetodipus   Rodent
29         leucopus        Peromyscus   Rodent
30      maniculatus        Peromyscus   Rodent
31     penicillatus       Chaetodipus   Rodent
32           fuscus            Pipilo     Bird
33              sp.       Chaetodipus   Rodent
34       fulvescens   Reithrodontomys   Rodent
35        megalotis   Reithrodontomys   Rodent
36         montanus   Reithrodontomys   Rodent
37              sp.   Reithrodontomys   Rodent
38        audubonii        Sylvilagus   Rabbit
39          breweri          Spizella     Bird
40           clarki        Sceloporus  Reptile
41      fulviventer          Sigmodon   Rodent
42         hispidus          Sigmodon   Rodent
43     ochrognathus          Sigmodon   Rodent
44        spilosoma      Spermophilus   Rodent
45     tereticaudus      Spermophilus   Rodent
46        undulatus        Sceloporus  Reptile
47              sp.          Sigmodon   Rodent
48              sp.            Lizard  Reptile
49              sp.            Pipilo     Bird
50              sp.            Rodent   Rodent
51              sp.           Sparrow     Bird
52       leucophrys       Zonotrichia     Bird
53         macroura           Zenaida     Bird

In [4]:
# select columns
pd.read_sql_query("""
    SELECT species, genus, taxa FROM species 
""", conn)

            species             genus     taxa
0         bilineata        Amphispiza     Bird
1           harrisi  Ammospermophilus   Rodent
2        savannarum        Ammodramus     Bird
3           taylori           Baiomys   Rodent
4   brunneicapillus   Campylorhynchus     Bird
5       melanocorys       Calamospiza     Bird
6          squamata        Callipepla     Bird
7        scutalatus          Crotalus  Reptile
8            tigris     Cnemidophorus  Reptile
9         uniparens     Cnemidophorus  Reptile
10          viridis          Crotalus  Reptile
11         merriami         Dipodomys   Rodent
12            ordii         Dipodomys   Rodent
13      spectabilis         Dipodomys   Rodent
14              sp.         Dipodomys   Rodent
15        obsoletus           Eumeces  Reptile
16            silus          Gambelia  Reptile
17         albigula           Neotoma   Rodent
18              sp.           Neotoma   Rodent
19      leucogaster         Onychomys   Rodent
20         torridus         Onychomys   Rodent
21              sp.         Onychomys   Rodent
22          baileyi       Chaetodipus   Rodent
23        chlorurus            Pipilo     Bird
24         eremicus        Peromyscus   Rodent
25           flavus       Perognathus   Rodent
26        gramineus         Pooecetes     Bird
27         hispidus       Perognathus   Rodent
28      intermedius       Chaetodipus   Rodent
29         leucopus        Peromyscus   Rodent
30      maniculatus        Peromyscus   Rodent
31     penicillatus       Chaetodipus   Rodent
32           fuscus            Pipilo     Bird
33              sp.       Chaetodipus   Rodent
34       fulvescens   Reithrodontomys   Rodent
35        megalotis   Reithrodontomys   Rodent
36         montanus   Reithrodontomys   Rodent
37              sp.   Reithrodontomys   Rodent
38        audubonii        Sylvilagus   Rabbit
39          breweri          Spizella     Bird
40           clarki        Sceloporus  Reptile
41      fulviventer          Sigmodon   Rodent
42         hispidus          Sigmodon   Rodent
43     ochrognathus          Sigmodon   Rodent
44        spilosoma      Spermophilus   Rodent
45     tereticaudus      Spermophilus   Rodent
46        undulatus        Sceloporus  Reptile
47              sp.          Sigmodon   Rodent
48              sp.            Lizard  Reptile
49              sp.            Pipilo     Bird
50              sp.            Rodent   Rodent
51              sp.           Sparrow     Bird
52       leucophrys       Zonotrichia     Bird
53         macroura           Zenaida     Bird

In [5]:
## select rows 
pd.read_sql_query("""
    SELECT * FROM species WHERE taxa = 'Bird'
""", conn)

   species_id            genus          species  taxa
0          AB       Amphispiza        bilineata  Bird
1          AS       Ammodramus       savannarum  Bird
2          CB  Campylorhynchus  brunneicapillus  Bird
3          CM      Calamospiza      melanocorys  Bird
4          CQ       Callipepla         squamata  Bird
5          PC           Pipilo        chlorurus  Bird
6          PG        Pooecetes        gramineus  Bird
7          PU           Pipilo           fuscus  Bird
8          SB         Spizella          breweri  Bird
9          UP           Pipilo              sp.  Bird
10         US          Sparrow              sp.  Bird
11         ZL      Zonotrichia       leucophrys  Bird
12         ZM          Zenaida         macroura  Bird

In [6]:
pd.read_sql_query("""
    SELECT DISTINCT taxa FROM species
""", conn)

      taxa
0     Bird
1   Rodent
2  Reptile
3   Rabbit

### exercise:
- select everything from the surveys TABLE
- select only the species_id and weight from the surveys TABLE
- select the distinct species_id from the surveys TABLE
- are there any species in the species table that aren't in the surveys table?
- select only rows with month = 12

In [7]:
pd.read_sql_query("""
    SELECT * FROM surveys
""", conn)

,record_id,month,day,year,plot_id,species_id,sex,hindfoot_length,weight
0,1,7,16,1977,2,NL,M,32.0,NaN
1,2,7,16,1977,3,NL,M,33.0,NaN
2,3,7,16,1977,2,DM,F,37.0,NaN
3,4,7,16,1977,7,DM,M,36.0,NaN
4,5,7,16,1977,3,DM,M,35.0,NaN
...,...,...,...,...,...,...,...,...,...
35544,35545,12,31,2002,15,AH,None,NaN,NaN
35545,35546,12,31,2002,15,AH,None,NaN,NaN
35546,35547,12,31,2002,10,RM,F,15.0,14.0
35547,35548,12,31,2002,7,DO,M,36.0,51.0
35548,35549,12,31,2002,5,None,None,NaN,NaN

In [8]:
pd.read_sql_query("""
    SELECT species_id, weight FROM surveys
""", conn)

      species_id  weight
0             NL     NaN
1             NL     NaN
2             DM     NaN
3             DM     NaN
4             DM     NaN
...          ...     ...
35544         AH     NaN
35545         AH     NaN
35546         RM    14.0
35547         DO    51.0
35548       None     NaN

[35549 rows x 2 columns]

In [9]:
pd.read_sql_query("""
    SELECT * FROM surveys WHERE month = 12
""", conn)

,record_id,month,day,year,plot_id,species_id,sex,hindfoot_length,weight
0,420,12,10,1977,13,DM,F,38.0,48.0
1,421,12,10,1977,9,DS,F,51.0,121.0
2,422,12,10,1977,2,DM,F,37.0,42.0
3,423,12,10,1977,13,DM,M,36.0,42.0
4,424,12,10,1977,2,DM,M,37.0,52.0
...,...,...,...,...,...,...,...,...,...
2794,35545,12,31,2002,15,AH,None,NaN,NaN
2795,35546,12,31,2002,15,AH,None,NaN,NaN
2796,35547,12,31,2002,10,RM,F,15.0,14.0
2797,35548,12,31,2002,7,DO,M,36.0,51.0
2798,35549,12,31,2002,5,None,None,NaN,NaN

In [10]:
pd.read_sql_query("""
    SELECT DISTINCT taxa FROM species
""", conn)

      taxa
0     Bird
1   Rodent
2  Reptile
3   Rabbit

In [11]:
pd.read_sql_query("""
    SELECT DISTINCT species_id FROM surveys
""", conn)

   species_id
0          NL
1          DM
2          PF
3          PE
4          DS
5          PP
6          SH
7          OT
8          DO
9          OX
10         SS
11         OL
12         RM
13       None
14         SA
15         PM
16         AH
17         DX
18         AB
19         CB
20         CM
21         CQ
22         RF
23         PC
24         PG
25         PH
26         PU
27         CV
28         UR
29         UP
30         ZL
31         UL
32         CS
33         SC
34         BA
35         SF
36         RO
37         AS
38         SO
39         PI
40         ST
41         CU
42         SU
43         RX
44         PB
45         PL
46         PX
47         CT
48         US

In [12]:
## compound WHERE clause
pd.read_sql_query("""
    SELECT * 
    FROM surveys
    WHERE 
    (species_id = 'DS' OR species_id = 'DO' ) AND (hindfoot_length > 50 OR weight < 100)
    ORDER BY hindfoot_length DESC
""", conn)

,record_id,month,day,year,plot_id,species_id,sex,hindfoot_length,weight
0,30425,3,4,2000,1,DO,F,64.0,35.0
1,1694,3,31,1979,8,DS,F,58.0,123.0
2,22049,2,4,1995,2,DO,M,58.0,51.0
3,3784,1,12,1981,1,DS,M,57.0,156.0
4,4449,5,4,1981,2,DS,F,57.0,136.0
...,...,...,...,...,...,...,...,...,...
4126,18587,4,20,1991,11,DO,F,NaN,63.0
4127,21968,12,5,1994,8,DO,M,NaN,37.0
4128,27191,11,22,1997,1,DO,M,NaN,48.0
4129,30284,2,5,2000,1,DO,M,NaN,53.0
4130,30442,3,4,2000,2,DO,F,NaN,66.0

### exercise:

- return everyting in month 1 OR 2 AND plot 8 or 9

In [ ]:
## compound WHERE clause
pd.read_sql_query("""
    SELECT * 
    FROM surveys
    WHERE
        (month = 1 OR month = 2) AND (plot_id = 9 OR plot_id = 9)
""", conn)

In [ ]:
# aggregations
# GROUP BY
# HAVING

# note I commwned out the requirement thata hindfoot_length > 30
# remove the -- to include this clause

## compound WHERE clause
pd.read_sql_query("""
    SELECT species_id, AVG(hindfoot_length)
    FROM surveys
    WHERE hindfoot_length IS NOT NULL
    GROUP BY species_id
    --HAVING AVG(hindfoot_length) > 30
    ORDER BY AVG(hindfoot_length) DESC
""", conn)

In [ ]:
## aggregations
# GROUP BY
# SUM, AVG, MAX, MIN, COUNT
# HAVING

pd.read_sql_query("""
    SELECT species_id, COUNT(species_id)
    FROM surveys
    GROUP BY species_id
    ORDER BY COUNT(species_id) DESC
""", conn)

### exercise
- count the number of taxa in the species table
- order in by count in descending order

In [ ]:
# note - using an alias for one of the column names

pd.read_sql_query("""
    SELECT taxa, COUNT(taxa) AS n_taxa
    FROM species
    GROUP BY taxa
    ORDER BY n_taxa DESC
""", conn)

### JOINS

- we can get the average hindfoot_length for each species_id
- what if I want it by genus, or taxa?

- start by JOINing
- then we'll aggregate

In [ ]:
pd.read_sql_query("""
    SELECT * 
    FROM species
    JOIN surveys
    ON species.species_id = surveys.species_id
    JOIN plots
    ON surveys.plot_id = plots.plot_id
""", conn)

### inner vs outer joins

Inner joins only include rows where both tables have a matching fow
Left Outer joins include all rows from the left table even if there is no match from the right table

recall there were a few species_id in the species table that weren't in the surveys TABLE.
We can use a LEFT OUTER join to include them in the result, even though there is no match in the species table

In [ ]:
pd.read_sql_query("""
    SELECT *
    FROM species
    LEFT JOIN surveys
    ON species.species_id = surveys.species_id
    ORDER BY record_id
    --WHERE record_id IS NULL
""", conn)